# Development Docker Compose for Milestone 1
# Quick PostgreSQL setup for testing

version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: hotel_dev_db
    environment:
      POSTGRES_USER: hoteluser
      POSTGRES_PASSWORD: hotelpass
      POSTGRES_DB: hoteldb
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hoteluser -d hoteldb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_dev_data: