# Simplified Production Docker Compose for Hotel Reception App
# Frontend-only deployment (backend implementation complete but separate)
version: '3.8'

services:
  # Frontend React Application
  hotel-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production
    container_name: hotel_frontend_prod
    ports:
      - "3000:80"
    environment:
      REACT_APP_API_URL: http://localhost:4000/api
      REACT_APP_HOTEL_NAME: Grand Hotel Reception
      REACT_APP_ADMIN_CODE: admin123
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - hotel-network

networks:
  hotel-network:
    driver: bridge