# Development Docker Compose for Hotel Reception App
# Includes hot-reload for frontend and backend

services:
  # PostgreSQL Database
  hotel-database:
    image: postgres:15-alpine
    container_name: hotel_dev_postgres
    environment:
      POSTGRES_USER: hoteluser
      POSTGRES_PASSWORD: hotelpass
      POSTGRES_DB: hoteldb
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - hotel_dev_postgres_data:/var/lib/postgresql/data
      - ./backups:/backups  # Mount backups directory
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hoteluser -d hoteldb"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - hotel-dev-network

  # Backend API (Development with hot-reload)
  hotel-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    container_name: hotel_dev_backend
    environment:
      NODE_ENV: development
      PORT: 4000
      DATABASE_URL: postgresql://hoteluser:hotelpass@hotel-database:5432/hoteldb
      CORS_ORIGIN: http://localhost:3000
    ports:
      - "4000:4000"
    depends_on:
      hotel-database:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/src/config:/app/src/config:ro
    networks:
      - hotel-dev-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend React App (Development with hot-reload)
  hotel-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    container_name: hotel_dev_frontend
    environment:
      REACT_APP_API_URL: http://localhost:4000/api
      REACT_APP_HOTEL_NAME: Grand Hotel Reception (Dev)
      REACT_APP_ADMIN_CODE: admin123
      CHOKIDAR_USEPOLLING: true
    ports:
      - "3000:3000"
    depends_on:
      hotel-backend:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - hotel-dev-network
    stdin_open: true
    tty: true

volumes:
  hotel_dev_postgres_data:
    driver: local

networks:
  hotel-dev-network:
    driver: bridge